name = "hayakuchi"
description = "A zola theme based on archie-zola."
license = "MIT"
homepage = "https://github.com/deepcodesoln/hayakuchi"
# The minimum version of Zola required
min_version = "0.19.1"
# An optional live demo URL
demo = ""

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "deepcode"
homepage = "https://deepcode.solutions"
